title: Mona Risa
author: Bo Turnbow
email: bo@turnbows.org
description: >
  Welcome to a blog for Mona Risa - Wharram Tiki 21 #924. Telling the story of a full rebuild and, hopefully, the further adventures.

show_excerpts: true

# generate social links in footer
github_username:  boturnbow
facebook_username: bo.turnbow
rss: rss

disqus:
    shortname: mona-risa

header_pages:
  - sitemap.md
  - about.md

theme: minima

# for sitemap plugin: the base hostname & protocol for your site
url: "https://monarisa.turnbows.org/"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
