title: Mona Risa
author: Bo Turnbow
email: bo@turnbows.org
description: >
  Wharram Tiki 21 #924

show_excerpts: true

minima:
  # generate social links in footer
  social_links:
    github: boturnbow
    facebook: bo.turnbow
    rss: rss

header_pages:
  - about.md

theme: minima
