title: Mona Risa
author: Bo Turnbow
email: bo@turnbows.org
description: >
  Welcome to a blog for *Mona Risa* - a Wharram Tiki 21 #924. Telling the story of a full rebuild and, hopefully, the further adventures.

show_excerpts: true

minima:
  # generate social links in footer
  social_links:
    github: boturnbow
    facebook: bo.turnbow
    rss: rss

header_pages:
  - about.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
