title: Mona Risa
author: Bo Turnbow
email: bo@turnbows.org
description: >
  Welcome to a blog for Mona Risa - Wharram Tiki 21 #924. Telling the story of a full rebuild and, hopefully, the further adventures.

show_excerpts: true

# generate social links in footer
github_username:  boturnbow
facebook_username: bo.turnbow
rss: rss

disqus:
    shortname: mona-risa

header_pages:
  - about.md
  - sitemap.html

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
